In [15]:
w1=[1.,2.,3.,4.]
w2=[4.,5.,6.,7.]
w3=[3.,2.,1.,1.]
W=[w1,w2,w3]
type(W)
len(W)
len(W[0])

4

In [14]:
v1=[1.,4.,4.,6.,5.]
v2=[1.,3.,1.,6.,2.]
v3=[6.,3.,4.,2.,1.]
v4=[1.,2.,4.,2.,3.]
V =[v1,v2,v3,v4]
type(V)
len(V)

4

In [49]:
def get_column(Z, col_index):
    temp = []
    for i in range(len(Z)):
        temp.append(Z[i][col_index])
    return temp

print(get_column(V, 1))
print(W[1])

[4.0, 3.0, 3.0, 2.0]
[4.0, 5.0, 6.0, 7.0]


In [51]:
def vector_multiplication(vector_1, vector_2):
    result = 0
    for i in range(len(vector_1)):
        result += vector_1[i] * vector_2[i]
    return result

vector_multiplication(get_column(V,1), W[1])

63.0

In [91]:
def multiply(W,V):
    col = len(V[0])
    row = len(W)
    temp_row = []
    result = []
        
    for r in range(row):
        for c in range(col):
            #print('Row:' + str(r) + ' Col: ' + str(c))
            #print(get_column(V,c))
            #print(W[r])
            #print(vector_multiplication(get_column(V,c), W[r]))
            #col[r][c] = vector_multiplication(get_column(V,c), W[r])
            temp_row.append(vector_multiplication(get_column(V,c), W[r]))
            if c == col -1:
                result.append(temp_row)
                temp_row = []
    return result
    
multiply(W, V)


[[25.0, 27.0, 34.0, 32.0, 24.0],
 [52.0, 63.0, 73.0, 80.0, 57.0],
 [12.0, 23.0, 22.0, 34.0, 23.0]]

In [97]:
import numpy as np
def test_multiply(W, V):
    X = multiply(W,V)
    # numpy version
    Y = np.dot(np.array(W), np.array(V))
    np.testing.assert_allclose(X, Y, rtol=1e-05)
    
test_multiply(W, V)

[[25.0, 27.0, 34.0, 32.0, 24.0], [52.0, 63.0, 73.0, 80.0, 57.0], [12.0, 23.0, 22.0, 34.0, 23.0]]
[[ 25.  27.  34.  32.  24.]
 [ 52.  63.  73.  80.  57.]
 [ 12.  23.  22.  34.  23.]]
