In [1]:
import numpy as np

np.random.randint(1, 7, size=20) # 20 mal würfeln 

array([1, 5, 6, 1, 2, 1, 3, 4, 5, 1, 6, 1, 1, 3, 1, 3, 6, 2, 4, 1])

In [2]:
ungerade_Wuerfelzahlen = {1, 3, 5}

if np.random.randint(1, 7) in ungerade_Wuerfelzahlen:
    print ("Ereignis ungerade Zahl eingetroffen.")
else:
    print ("Ereignis ungerade Zahl nicht eingetroffen.")



Ereignis ungerade Zahl nicht eingetroffen.


In [3]:
a = np.arange(15).reshape(3, 5)
print(a) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
a.shape #Command 

(3, 5)

In [18]:
a = np.ones(50).reshape(2,5,5)
a *=2


b = np.array([[2,3],
              [5,6]])

c = np.array([[2,4],
              [5,2]])



array([[19, 14],
       [40, 32]])